# 缓存配置
spring:
  cache:
    cache-names: c1, c2
    redis:
      time-to-live: 1800s

  redis:
    database: 0
    host: 192.168.197.130
    pool: 6379
    password: password
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: -1ms
        min-idle: 0