spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql:///vhrdb?serverTimezone=GMT
    username: root
    password: password
mybatis:
  mapper-locations: classpath:mapper/*.xml

server:
  port: 8082
