server:
  port: 8081

  error:
    path: /error

  servlet:
    session:
      timeout: 30m
    context-path: /chapter

  tomcat:
    uri-encoding: utf-8
    max-threads: 500

  ssl:
    key-store: strr0.p12
    key-alias: tomcathttps
    key-password: 123456


book:
  name: 三国演义
  author: 罗贯中
  price: 30

my:
  name: strr
  address: China
  favorites:
    - 足球
    - 徒步
    - Coding
