spring:
  redis:
    cluster:
      ports:
        - 8001
        - 8002
        - 8003
        - 8004
        - 8005
        - 8006
      host: 192.168.197.130
      poolConfig:
        max-total: 6
        max-idle: 6
        max-wait-millis: -1
        min-idle: 0
